{
  "errors" : [ {
    "title" : "Empty Dockerfile",
    "filePath" : "Dockerfile",
    "lineStart" : null,
    "lineEnd" : null,
    "severity" : "ERROR"
  } ],
  "improvements" : [ ],
  "thingsDoneRight" : [ ]
}